<?php

namespace Damis\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
*
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametervalueRepository extends EntityRepository
{
    public function getOrderedParameters($workflowTask)
    {
        $query = $this->createQueryBuilder('pv')
            ->select('pv')
            ->leftJoin('pv.parameter', 'p')
            ->andWhere('pv.workflowtask = :w')
            ->setParameter('w', $workflowTask)
            ->addOrderBy('p.position', 'ASC');

        return $query->getQuery()->getResult();
    }
}
