<?php

namespace Damis\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
*
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowtaskRepository extends EntityRepository
{
    public function getRunnableTasks($limit)
    {
        $query = $this->createQueryBuilder('w')
            ->select('w')
            ->leftJoin('w.experiment', 'e')
            ->leftJoin('DamisEntitiesBundle:Parametervalue', 'pv', 'with', 'pv.workflowtask = w')
            ->leftJoin('DamisEntitiesBundle:Pvalueoutpvaluein', 'pio', 'with', 'pv.parametervalueid = pio.inparametervalue')
            ->andWhere('e.status = 2')
            ->andWhere('w.workflowtaskisrunning = 0')
            ->andWhere('pio.outparametervalue IS NOT NULL')
            ->andWhere('pv.parametervalue IS NOT NULL')
            ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }
}
