<?php

namespace Base\StaticBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function getMaxTextPosition()
    {
        $query = $this->createQueryBuilder('p')
            ->select('max(p.position) as max_position');

        return $query->getQuery()->getOneOrNullResult();
    }

    public function getNextUpPosition($newPosition)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->andWhere('p.position <= :new_position')
            ->orderBy('p.position', 'DESC')
            ->setParameter('new_position', $newPosition)
            ->setMaxResults(1);

        return $query->getQuery()->getOneOrNullResult();
    }

    public function getNextDownPosition($newPosition)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->andWhere('p.position >= :new_position')
            ->orderBy('p.position', 'ASC')
            ->setParameter('new_position', $newPosition)
            ->setMaxResults(1);

        return $query->getQuery()->getOneOrNullResult();
    }
}
