<?php

namespace Damis\ExperimentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
*
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends EntityRepository
{
    public function getTasksComponent($task)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.parameters', 'p')
            ->leftJoin('DamisEntitiesBundle:Parametervalue', 'pv', 'with', 'pv.parameter = p')
            ->andWhere('pv.workflowtask = :wid')
            ->setParameter('wid', $task->getWorkflowtaskid())
        ;

        return $query->getQuery()->getOneOrNullResult();
    }
}
