<?php

namespace Damis\ExperimentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Damis\EntitiesBundle\Entity\Parametervalue;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends EntityRepository
{
    /**
     * Finds component of specified task(id)
     * @param $task
     * @return mixed
     */
    public function getTasksComponent($task)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.parameters', 'p')
            ->leftJoin(Parametervalue::class, 'pv', 'with', 'pv.parameter = p')
            ->andWhere('pv.workflowtask = :wid')
            ->setParameter('wid', $task->getWorkflowtaskid())
        ;

        return $query->getQuery()->getOneOrNullResult();
    }
}