<?php

namespace Damis\ExperimentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Base\UserBundle\Entity\User;
use Damis\ExperimentBundle\Entity\Experiment;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperimentRepository extends EntityRepository
{
    /**
     * Finds specified limit of closable experiments (which have all successfully finished tasks) - for successfully finishing
     *
     * @param $limit
     * @return array
     */
    public function getClosableExperiments($limit = 100)
    {
        $query = $this->createQueryBuilder('e')
            ->select('e')
            ->leftJoin('e.workflowtasks', 'w', 'with', 'w.experiment = e and (w.workflowtaskisrunning = 0 or w.workflowtaskisrunning = 1 or w.workflowtaskisrunning = 3)')
            ->andWhere('e.status = 2')
            ->andWhere('w.workflowtaskid is null')
            ->andWhere('e.start < CURRENT_TIMESTAMP()')
            ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

    /**
     * Finds specified limit of closable experiments (which have at least one task with error status) - for error status
     *
     * @param int $limit
     * @return array
     */
    public function getClosableErrExperiments($limit = 100)
    {
        $query = $this->createQueryBuilder('e')
            ->select('e')
            ->leftJoin('e.workflowtasks', 'w', 'with', 'w.experiment = e and w.workflowtaskisrunning = 3')
            ->andWhere('e.status = 2')
            ->andWhere('w.workflowtaskid is not null')
            ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }

    /**
     * Returns all user experiments
     *
     * @param User $user
     * @return Query
     */
    public function getUserExperiments(User $user)
    {
        $query = $this->createQueryBuilder('e')
            ->select('e')
            ->andWhere('e.user = :user')
            ->andWhere('e.status <> 6')
            ->setParameter('user', $user)
            ->addOrderBy('e.id', 'DESC');

        return $query->getQuery();
    }

    /**
     * Returns all experiment examples
     *
     * @return Query
     */
    public function getExperimentsExamples()
    {
        $query = $this->createQueryBuilder('e')
            ->select('e')
            ->andWhere('e.status = 6')
            ->addOrderBy('e.id', 'DESC');

        return $query->getQuery();
    }

    /**
     * Gets the next available experiment number for a user (e.g., '001', '012', '123').
     *
     * @param User $user
     * @return string
     */
    public function getNextExperimentNameNumber(User $user): string
    {
        $dql = "
            SELECT SUBSTRING(tbl.name, 4) as nr
            FROM " . Experiment::class . " tbl
            WHERE SUBSTRING(tbl.name, 1, 3) = 'exp' AND tbl.user = :user
            ORDER BY tbl.id DESC
        ";

        $query = $this->getEntityManager()->createQuery($dql);

        $query->setParameter('user', $user);
        $query->setMaxResults(1);

        $result = $query->getOneOrNullResult();

        $nextNumber = $result ? ((int)$result['nr'] + 1) : 1;

        return str_pad((string) $nextNumber, 3, '0', STR_PAD_LEFT);
    }
}